import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore, collection, doc, setDoc, Timestamp } from 'firebase/firestore';
import fs from 'fs';
import path from 'path';

const config = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'firebase-applet-config.json'), 'utf-8'));
const app = !getApps().length ? initializeApp(config) : getApp();
const db = config.firestoreDatabaseId 
  ? getFirestore(app, config.firestoreDatabaseId) 
  : getFirestore(app);

const DRIVERS = [
  {
    id: "LD-101",
    name: "Jordan Daniels",
    phone: "+60 12-234 5678",
    pin: "2048",
    vehicle: "Perodua Aruz (Lady Fleet)",
    vehicleModel: "Perodua Aruz 1.5 AV",
    licensePlate: "WVP 8821",
    status: "on_duty",
    isAvailable: true,
    adminRole: false,
    totalCompletedJobs: 148,
    rating: 4.96
  },
  {
    id: "LD-102",
    name: "Nadia Rahman",
    phone: "+60 13-345 6789",
    pin: "1188",
    vehicle: "Honda City RS",
    vehicleModel: "Honda City 1.5 e:HEV RS",
    licensePlate: "VLU 9902",
    status: "on_duty",
    isAvailable: true,
    adminRole: false,
    totalCompletedJobs: 112,
    rating: 4.92
  },
  {
    id: "LD-103",
    name: "Sofia Lim",
    phone: "+60 16-876 5432",
    pin: "3110",
    vehicle: "Nissan Almera Turbo",
    vehicleModel: "Nissan Almera 1.0 VL",
    licensePlate: "WKE 3310",
    status: "on_duty",
    isAvailable: false,
    adminRole: false,
    totalCompletedJobs: 95,
    rating: 4.88
  },
  {
    id: "LD-104",
    name: "Aisha Karim",
    phone: "+60 17-999 0011",
    pin: "8888",
    vehicle: "Toyota Vios Premium",
    vehicleModel: "Toyota Vios 1.5G",
    licensePlate: "VPR 5050",
    status: "on_duty",
    isAvailable: true,
    adminRole: true,
    totalCompletedJobs: 215,
    rating: 4.99
  },
  {
    id: "LD-105",
    name: "Mei Ling Tan",
    phone: "+60 12-671 2299",
    pin: "1111",
    vehicle: "Proton X50 Flagship",
    vehicleModel: "Proton X50 1.5 TGDi",
    licensePlate: "WBM 7744",
    status: "on_duty",
    isAvailable: true,
    adminRole: false,
    totalCompletedJobs: 84,
    rating: 4.89
  },
  {
    id: "LD-106",
    name: "Nurul Huda",
    phone: "+60 19-456 7890",
    pin: "4321",
    vehicle: "Perodua Ativa",
    vehicleModel: "Perodua Ativa 1.0 Turbo AV",
    licensePlate: "VQS 1208",
    status: "on_duty",
    isAvailable: true,
    adminRole: false,
    totalCompletedJobs: 73,
    rating: 4.94
  },
  {
    id: "LD-107",
    name: "Hannah Fernandez",
    phone: "+60 14-888 1234",
    pin: "5555",
    vehicle: "Hyundai Elantra",
    vehicleModel: "Hyundai Elantra 1.6 Premium",
    licensePlate: "VKH 6620",
    status: "off_duty",
    isAvailable: false,
    adminRole: false,
    totalCompletedJobs: 56,
    rating: 4.85
  },
  {
    id: "LD-108",
    name: "Grace Wong",
    phone: "+60 18-333 4455",
    pin: "9090",
    vehicle: "Mazda 3 Hatchback",
    vehicleModel: "Mazda 3 2.0 High Plus",
    licensePlate: "WMA 3399",
    status: "off_duty",
    isAvailable: false,
    adminRole: false,
    totalCompletedJobs: 42,
    rating: 4.91
  }
];

const TRIPS = [
  {
    id: "TRP-2026-9001",
    passengerName: "Nur Aishah",
    passengerPhone: "+60 12-384 9912",
    passengerCount: 1,
    pickupAddress: "The Horizon, Bangsar South",
    dropoffAddress: "KL Sentral Departure Hall",
    route: "The Horizon, Bangsar South → KL Sentral",
    pickupDate: "2026-10-01",
    pickupTime: "08:15",
    fare: 28.50,
    paymentAmount: 28.50,
    paymentDriver: 22.80,
    grossProfit: 5.70,
    status: "completed",
    statusOps: "COMPLETED",
    statusAdmin: "PAID",
    driverId: "LD-101",
    driverName: "Jordan Daniels",
    assignedDriverId: "LD-101",
    assignedDriverName: "Jordan Daniels",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 6.8,
    specialNotes: "Quiet ride preferred. Flight connection.",
    time: "08:15 AM",
    minutesAgo: 320
  },
  {
    id: "TRP-2026-9002",
    passengerName: "Siti Zulaikha",
    passengerPhone: "+60 13-921 4455",
    passengerCount: 2,
    pickupAddress: "KLCC Suria Tower, Kuala Lumpur",
    dropoffAddress: "Pavilion Damansara Heights",
    route: "KLCC Suria → Pavilion Damansara Heights",
    pickupDate: "2026-10-01",
    pickupTime: "08:45",
    fare: 38.00,
    paymentAmount: 38.00,
    paymentDriver: 30.40,
    grossProfit: 7.60,
    status: "completed",
    statusOps: "COMPLETED",
    statusAdmin: "PAID",
    driverId: "LD-102",
    driverName: "Nadia Rahman",
    assignedDriverId: "LD-102",
    assignedDriverName: "Nadia Rahman",
    vehicleType: "EXECUTIVE_SEDAN",
    estimatedDistanceKm: 11.2,
    specialNotes: "Two suitcases in boot.",
    time: "08:45 AM",
    minutesAgo: 290
  },
  {
    id: "TRP-2026-9003",
    passengerName: "Amanda Lin",
    passengerPhone: "+60 12-443 2211",
    passengerCount: 1,
    pickupAddress: "Mid Valley Megamall North Court",
    dropoffAddress: "Mont Kiara Pines Condominium",
    route: "Mid Valley Megamall → Mont Kiara Pines",
    pickupDate: "2026-10-01",
    pickupTime: "09:10",
    fare: 32.50,
    paymentAmount: 32.50,
    paymentDriver: 26.00,
    grossProfit: 6.50,
    status: "completed",
    statusOps: "COMPLETED",
    statusAdmin: "PAID",
    driverId: "LD-104",
    driverName: "Aisha Karim",
    assignedDriverId: "LD-104",
    assignedDriverName: "Aisha Karim",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 9.4,
    specialNotes: "Pick up at North Court lobby.",
    time: "09:10 AM",
    minutesAgo: 260
  },
  {
    id: "TRP-2026-9004",
    passengerName: "Melissa Wong",
    passengerPhone: "+60 17-234 8877",
    passengerCount: 3,
    pickupAddress: "1 Utama Shopping Centre, Petaling Jaya",
    dropoffAddress: "Taman Rimba Kiara, TTDI",
    route: "1 Utama Shopping Centre → TTDI Park",
    pickupDate: "2026-10-01",
    pickupTime: "09:30",
    fare: 22.00,
    paymentAmount: 22.00,
    paymentDriver: 17.60,
    grossProfit: 4.40,
    status: "completed",
    statusOps: "COMPLETED",
    statusAdmin: "PAID",
    driverId: "LD-105",
    driverName: "Mei Ling Tan",
    assignedDriverId: "LD-105",
    assignedDriverName: "Mei Ling Tan",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 4.5,
    specialNotes: "Family outing with daughter.",
    time: "09:30 AM",
    minutesAgo: 240
  },
  {
    id: "TRP-2026-9005",
    passengerName: "Priya Nair",
    passengerPhone: "+60 16-555 7821",
    passengerCount: 1,
    pickupAddress: "Sunway Pyramid Main Entrance",
    dropoffAddress: "SS15 Courtyard, Subang Jaya",
    route: "Sunway Pyramid → Subang Jaya SS15",
    pickupDate: "2026-10-01",
    pickupTime: "10:00",
    fare: 24.00,
    paymentAmount: 24.00,
    paymentDriver: 19.20,
    grossProfit: 4.80,
    status: "completed",
    statusOps: "COMPLETED",
    statusAdmin: "PAID",
    driverId: "LD-106",
    driverName: "Nurul Huda",
    assignedDriverId: "LD-106",
    assignedDriverName: "Nurul Huda",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 5.2,
    specialNotes: "Student commuter.",
    time: "10:00 AM",
    minutesAgo: 210
  },
  {
    id: "TRP-2026-9006",
    passengerName: "Farah Diana",
    passengerPhone: "+60 19-876 1234",
    passengerCount: 2,
    pickupAddress: "Lot 10 Shopping Centre, Bukit Bintang",
    dropoffAddress: "Bangsar Village II, Jalan Telawi",
    route: "Bukit Bintang Lot 10 → Bangsar Village II",
    pickupDate: "2026-10-01",
    pickupTime: "10:30",
    fare: 31.00,
    paymentAmount: 31.00,
    paymentDriver: 24.80,
    grossProfit: 6.20,
    status: "completed",
    statusOps: "COMPLETED",
    statusAdmin: "PAID",
    driverId: "LD-101",
    driverName: "Jordan Daniels",
    assignedDriverId: "LD-101",
    assignedDriverName: "Jordan Daniels",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 8.1,
    specialNotes: "Shopping bags assistance.",
    time: "10:30 AM",
    minutesAgo: 180
  },
  {
    id: "TRP-2026-9007",
    passengerName: "Rachel Tan",
    passengerPhone: "+60 12-901 3344",
    passengerCount: 1,
    pickupAddress: "Plaza Damas, Sri Hartamas",
    dropoffAddress: "Menara Citibank, Jalan Ampang",
    route: "Plaza Damas → Menara Citibank, Jalan Ampang",
    pickupDate: "2026-10-01",
    pickupTime: "11:00",
    fare: 35.00,
    paymentAmount: 35.00,
    paymentDriver: 28.00,
    grossProfit: 7.00,
    status: "completed",
    statusOps: "COMPLETED",
    statusAdmin: "PAID",
    driverId: "LD-102",
    driverName: "Nadia Rahman",
    assignedDriverId: "LD-102",
    assignedDriverName: "Nadia Rahman",
    vehicleType: "EXECUTIVE_SEDAN",
    estimatedDistanceKm: 10.5,
    specialNotes: "Corporate meeting commute.",
    time: "11:00 AM",
    minutesAgo: 150
  },
  {
    id: "TRP-2026-9008",
    passengerName: "Jasmine Kaur",
    passengerPhone: "+60 14-772 9001",
    passengerCount: 2,
    pickupAddress: "Publika Shopping Gallery, Solaris Dutamas",
    dropoffAddress: "The Waterfront, Desa ParkCity",
    route: "Publika Shopping Gallery → Desa ParkCity",
    pickupDate: "2026-10-01",
    pickupTime: "11:25",
    fare: 26.50,
    paymentAmount: 26.50,
    paymentDriver: 21.20,
    grossProfit: 5.30,
    status: "completed",
    statusOps: "COMPLETED",
    statusAdmin: "PAID",
    driverId: "LD-104",
    driverName: "Aisha Karim",
    assignedDriverId: "LD-104",
    assignedDriverName: "Aisha Karim",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 6.2,
    specialNotes: "Small pet carrier enclosed.",
    time: "11:25 AM",
    minutesAgo: 125
  },
  {
    id: "TRP-2026-9009",
    passengerName: "Chloe Lee",
    passengerPhone: "+60 11-2345 6789",
    passengerCount: 1,
    pickupAddress: "Sultan Abdul Aziz Shah Airport (SZB)",
    dropoffAddress: "Aloft Kuala Lumpur Sentral",
    route: "Subang Airport (SZB) → Nu Sentral Hotel",
    pickupDate: "2026-10-01",
    pickupTime: "11:50",
    fare: 48.00,
    paymentAmount: 48.00,
    paymentDriver: 38.40,
    grossProfit: 9.60,
    status: "completed",
    statusOps: "COMPLETED",
    statusAdmin: "PAID",
    driverId: "LD-105",
    driverName: "Mei Ling Tan",
    assignedDriverId: "LD-105",
    assignedDriverName: "Mei Ling Tan",
    vehicleType: "EXECUTIVE_SEDAN",
    estimatedDistanceKm: 21.3,
    specialNotes: "Arrival flight Firefly FY-2201.",
    time: "11:50 AM",
    minutesAgo: 100
  },
  {
    id: "TRP-2026-9010",
    passengerName: "Wan Nadiah",
    passengerPhone: "+60 13-441 5566",
    passengerCount: 1,
    pickupAddress: "Empire Shopping Gallery, Subang",
    dropoffAddress: "Paradigm Mall, Kelana Jaya",
    route: "Empire Shopping Gallery → Paradigm Mall",
    pickupDate: "2026-10-01",
    pickupTime: "12:15",
    fare: 25.00,
    paymentAmount: 25.00,
    paymentDriver: 20.00,
    grossProfit: 5.00,
    status: "completed",
    statusOps: "COMPLETED",
    statusAdmin: "PAID",
    driverId: "LD-106",
    driverName: "Nurul Huda",
    assignedDriverId: "LD-106",
    assignedDriverName: "Nurul Huda",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 7.9,
    specialNotes: "Lunch appointment.",
    time: "12:15 PM",
    minutesAgo: 75
  },
  {
    id: "TRP-2026-9011",
    passengerName: "Anis Syahirah",
    passengerPhone: "+60 18-912 3456",
    passengerCount: 1,
    pickupAddress: "The Gardens Mall Lobby, Mid Valley",
    dropoffAddress: "The St. Regis Kuala Lumpur",
    route: "The Gardens Mall → St. Regis Kuala Lumpur",
    pickupDate: "2026-10-01",
    pickupTime: "12:35",
    fare: 34.00,
    paymentAmount: 34.00,
    paymentDriver: 27.20,
    grossProfit: 6.80,
    status: "in_progress",
    statusOps: "IN_TRANSIT",
    statusAdmin: "APPROVED",
    driverId: "LD-101",
    driverName: "Jordan Daniels",
    assignedDriverId: "LD-101",
    assignedDriverName: "Jordan Daniels",
    vehicleType: "EXECUTIVE_SEDAN",
    estimatedDistanceKm: 5.8,
    specialNotes: "En route along Jalan Damansara.",
    time: "12:35 PM",
    minutesAgo: 45
  },
  {
    id: "TRP-2026-9012",
    passengerName: "Jessica Gomez",
    passengerPhone: "+60 12-777 6655",
    passengerCount: 2,
    pickupAddress: "Tropicana Gardens Mall, Kota Damansara",
    dropoffAddress: "Dataran Sunway, Kota Damansara",
    route: "Tropicana Gardens Mall → Dataran Sunway",
    pickupDate: "2026-10-01",
    pickupTime: "12:45",
    fare: 18.00,
    paymentAmount: 18.00,
    paymentDriver: 14.40,
    grossProfit: 3.60,
    status: "in_progress",
    statusOps: "IN_TRANSIT",
    statusAdmin: "APPROVED",
    driverId: "LD-102",
    driverName: "Nadia Rahman",
    assignedDriverId: "LD-102",
    assignedDriverName: "Nadia Rahman",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 3.1,
    specialNotes: "Short hop to banking hall.",
    time: "12:45 PM",
    minutesAgo: 35
  },
  {
    id: "TRP-2026-9013",
    passengerName: "Siti Hajar",
    passengerPhone: "+60 17-654 3210",
    passengerCount: 1,
    pickupAddress: "Solaris Dutamas Block A",
    dropoffAddress: "The Intermark, Jalan Tun Razak",
    route: "Solaris Dutamas → Intermark Mall, Jalan Tun Razak",
    pickupDate: "2026-10-01",
    pickupTime: "13:00",
    fare: 33.00,
    paymentAmount: 33.00,
    paymentDriver: 26.40,
    grossProfit: 6.60,
    status: "in_progress",
    statusOps: "IN_TRANSIT",
    statusAdmin: "APPROVED",
    driverId: "LD-103",
    driverName: "Sofia Lim",
    assignedDriverId: "LD-103",
    assignedDriverName: "Sofia Lim",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 9.6,
    specialNotes: "Approaching Mahameru highway.",
    time: "01:00 PM",
    minutesAgo: 20
  },
  {
    id: "TRP-2026-9014",
    passengerName: "Kavita Devi",
    passengerPhone: "+60 19-333 7788",
    passengerCount: 3,
    pickupAddress: "Plaza Arkadia, Desa ParkCity",
    dropoffAddress: "Central Park, Bandar Utama",
    route: "Plaza Arkadia → Bandar Utama Central Park",
    pickupDate: "2026-10-01",
    pickupTime: "13:10",
    fare: 27.50,
    paymentAmount: 27.50,
    paymentDriver: 22.00,
    grossProfit: 5.50,
    status: "assigned",
    statusOps: "ASSIGNED",
    statusAdmin: "CONFIRMED",
    driverId: "LD-104",
    driverName: "Aisha Karim",
    assignedDriverId: "LD-104",
    assignedDriverName: "Aisha Karim",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 7.5,
    specialNotes: "Driver arrived at Plaza Arkadia main fountain.",
    time: "01:10 PM",
    minutesAgo: 15
  },
  {
    id: "TRP-2026-9015",
    passengerName: "Brenda Teoh",
    passengerPhone: "+60 12-889 4433",
    passengerCount: 1,
    pickupAddress: "Starhill Gallery, Jalan Bukit Bintang",
    dropoffAddress: "Four Seasons Hotel Kuala Lumpur",
    route: "Starhill Gallery → Four Seasons Hotel KL",
    pickupDate: "2026-10-01",
    pickupTime: "13:15",
    fare: 29.00,
    paymentAmount: 29.00,
    paymentDriver: 23.20,
    grossProfit: 5.80,
    status: "assigned",
    statusOps: "ASSIGNED",
    statusAdmin: "CONFIRMED",
    driverId: "LD-105",
    driverName: "Mei Ling Tan",
    assignedDriverId: "LD-105",
    assignedDriverName: "Mei Ling Tan",
    vehicleType: "EXECUTIVE_SEDAN",
    estimatedDistanceKm: 3.8,
    specialNotes: "VIP guest pickup.",
    time: "01:15 PM",
    minutesAgo: 10
  },
  {
    id: "TRP-2026-9016",
    passengerName: "Natalie Chen",
    passengerPhone: "+60 16-112 9900",
    passengerCount: 2,
    pickupAddress: "Bangsar Shopping Centre (BSC) Main Foyer",
    dropoffAddress: "UM Medical Centre (PPUM), Petaling Jaya",
    route: "Bangsar Shopping Centre → UM Medical Centre",
    pickupDate: "2026-10-01",
    pickupTime: "13:20",
    fare: 26.00,
    paymentAmount: 26.00,
    paymentDriver: 20.80,
    grossProfit: 5.20,
    status: "assigned",
    statusOps: "ASSIGNED",
    statusAdmin: "CONFIRMED",
    driverId: "LD-106",
    driverName: "Nurul Huda",
    assignedDriverId: "LD-106",
    assignedDriverName: "Nurul Huda",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 6.4,
    specialNotes: "Assisting senior passenger into vehicle.",
    time: "01:20 PM",
    minutesAgo: 5
  },
  {
    id: "TRP-2026-9017",
    passengerName: "Zainab Omar",
    passengerPhone: "+60 13-776 5544",
    passengerCount: 1,
    pickupAddress: "IOI City Mall, Putrajaya",
    dropoffAddress: "Shaftsbury Square, Cyberjaya",
    route: "IOI City Mall → Cyberjaya Shaftsbury Square",
    pickupDate: "2026-10-01",
    pickupTime: "13:25",
    fare: 36.00,
    paymentAmount: 36.00,
    paymentDriver: 28.80,
    grossProfit: 7.20,
    status: "pending",
    statusOps: "UNASSIGNED",
    statusAdmin: "PENDING",
    driverId: "",
    driverName: "",
    assignedDriverId: "",
    assignedDriverName: "",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 14.2,
    specialNotes: "Looking for available lady driver near Putrajaya.",
    time: "01:25 PM",
    minutesAgo: 3
  },
  {
    id: "TRP-2026-9018",
    passengerName: "Karen Low",
    passengerPhone: "+60 12-554 1122",
    passengerCount: 1,
    pickupAddress: "LRT Kelana Jaya Station Entrance B",
    dropoffAddress: "Sunway Geo Avenue, Bandar Sunway",
    route: "LRT Kelana Jaya → Sunway Geo Avenue",
    pickupDate: "2026-10-01",
    pickupTime: "13:28",
    fare: 23.50,
    paymentAmount: 23.50,
    paymentDriver: 18.80,
    grossProfit: 4.70,
    status: "pending",
    statusOps: "UNASSIGNED",
    statusAdmin: "PENDING",
    driverId: "",
    driverName: "",
    assignedDriverId: "",
    assignedDriverName: "",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 5.9,
    specialNotes: "Standing by pick-up shelter.",
    time: "01:28 PM",
    minutesAgo: 2
  },
  {
    id: "TRP-2026-9019",
    passengerName: "Elena Rostova",
    passengerPhone: "+60 14-222 8899",
    passengerCount: 2,
    pickupAddress: "Hartamas Shopping Centre Lobby",
    dropoffAddress: "Sentul Depot, Sentul West",
    route: "Hartamas Shopping Centre → Sentul Depot",
    pickupDate: "2026-10-01",
    pickupTime: "13:30",
    fare: 27.00,
    paymentAmount: 27.00,
    paymentDriver: 21.60,
    grossProfit: 5.40,
    status: "pending",
    statusOps: "UNASSIGNED",
    statusAdmin: "PENDING",
    driverId: "",
    driverName: "",
    assignedDriverId: "",
    assignedDriverName: "",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 8.7,
    specialNotes: "Art gallery opening event.",
    time: "01:30 PM",
    minutesAgo: 1
  },
  {
    id: "TRP-2026-9020",
    passengerName: "Sarah Jenkins",
    passengerPhone: "+60 17-889 0012",
    passengerCount: 2,
    pickupAddress: "The Exchange TRX Main Dropoff",
    dropoffAddress: "MyTOWN Shopping Centre, Cheras",
    route: "TRX Exchange Mall → MyTOWN Shopping Centre",
    pickupDate: "2026-10-01",
    pickupTime: "11:40",
    fare: 25.50,
    paymentAmount: 25.50,
    paymentDriver: 20.40,
    grossProfit: 5.10,
    status: "disputed",
    statusOps: "DISPUTED",
    statusAdmin: "DISPUTED",
    driverId: "LD-103",
    driverName: "Sofia Lim",
    assignedDriverId: "LD-103",
    assignedDriverName: "Sofia Lim",
    vehicleType: "STANDARD_SEDAN",
    estimatedDistanceKm: 3.5,
    specialNotes: "Route detour dispute: passenger queried toll gate detour.",
    time: "11:40 AM",
    minutesAgo: 110
  }
];

async function seed() {
  console.log("Seeding 8 Drivers to Firestore...");
  for (const driver of DRIVERS) {
    await setDoc(doc(db, "drivers", driver.id), {
      id: driver.id,
      name: driver.name,
      vehicle: driver.vehicle,
      vehicleModel: driver.vehicleModel,
      licensePlate: driver.licensePlate,
      phone: driver.phone,
      status: driver.status,
      isAvailable: driver.isAvailable,
      rating: driver.rating,
      totalCompletedJobs: driver.totalCompletedJobs
    });
  }
  console.log("✓ Successfully seeded 8 Drivers into Firestore.");

  console.log("Seeding 20 Dummy Trips to Firestore...");
  const now = Date.now();
  for (const trip of TRIPS) {
    const tripCreatedAt = new Date(now - trip.minutesAgo * 60 * 1000);
    const firestoreData = {
      id: trip.id,
      route: trip.route,
      fare: trip.fare,
      status: trip.status,
      driverId: trip.driverId || "",
      driverName: trip.driverName || "",
      passengerName: trip.passengerName,
      passengerPhone: trip.passengerPhone,
      passengerCount: trip.passengerCount,
      pickupAddress: trip.pickupAddress,
      dropoffAddress: trip.dropoffAddress,
      pickupDate: trip.pickupDate,
      pickupTime: trip.pickupTime,
      vehicleType: trip.vehicleType,
      estimatedDistanceKm: trip.estimatedDistanceKm,
      paymentAmount: trip.paymentAmount,
      paymentDriver: trip.paymentDriver,
      grossProfit: trip.grossProfit,
      statusOps: trip.statusOps,
      statusAdmin: trip.statusAdmin,
      assignedDriverId: trip.assignedDriverId || "",
      assignedDriverName: trip.assignedDriverName || "",
      specialNotes: trip.specialNotes,
      time: trip.time,
      createdAt: Timestamp.fromDate(tripCreatedAt),
      updatedAt: Timestamp.fromDate(new Date(now - (trip.minutesAgo - 10) * 60 * 1000))
    };

    await setDoc(doc(db, "trips", trip.id), firestoreData);
  }
  console.log("✓ Successfully seeded 20 Dummy Trips into Firestore.");

  // Also update local_db.json
  const dbFile = path.join(process.cwd(), 'local_db.json');
  let localDb = {
    drivers: DRIVERS,
    trips: TRIPS.map(trip => {
      const tripCreatedAt = new Date(now - trip.minutesAgo * 60 * 1000).toISOString();
      return {
        id: trip.id,
        passengerName: trip.passengerName,
        passengerPhone: trip.passengerPhone,
        passengerCount: trip.passengerCount,
        pickupAddress: trip.pickupAddress,
        dropoffAddress: trip.dropoffAddress,
        pickupDate: trip.pickupDate,
        pickupTime: trip.pickupTime,
        isRoundTrip: false,
        vehicleType: trip.vehicleType,
        estimatedDistanceKm: trip.estimatedDistanceKm,
        paymentAmount: trip.paymentAmount,
        paymentDriver: trip.paymentDriver,
        grossProfit: trip.grossProfit,
        statusOps: trip.statusOps,
        statusAdmin: trip.statusAdmin,
        assignedDriverId: trip.assignedDriverId,
        assignedDriverName: trip.assignedDriverName,
        specialNotes: trip.specialNotes,
        createdAt: tripCreatedAt,
        updatedAt: new Date(now - (trip.minutesAgo - 10) * 60 * 1000).toISOString(),
        completedAt: trip.status === 'completed' ? new Date(now - (trip.minutesAgo - 25) * 60 * 1000).toISOString() : undefined
      };
    }),
    activityLogs: [
      {
        id: "ACT-9001",
        tripId: "TRP-2026-9001",
        driverName: "Jordan Daniels",
        route: "The Horizon, Bangsar South → KL Sentral",
        payout: 22.80,
        timestamp: new Date(now - 295 * 60 * 1000).toISOString()
      },
      {
        id: "ACT-9002",
        tripId: "TRP-2026-9002",
        driverName: "Nadia Rahman",
        route: "KLCC Suria → Pavilion Damansara Heights",
        payout: 30.40,
        timestamp: new Date(now - 265 * 60 * 1000).toISOString()
      },
      {
        id: "ACT-9003",
        tripId: "TRP-2026-9003",
        driverName: "Aisha Karim",
        route: "Mid Valley Megamall → Mont Kiara Pines",
        payout: 26.00,
        timestamp: new Date(now - 235 * 60 * 1000).toISOString()
      },
      {
        id: "ACT-9004",
        tripId: "TRP-2026-9004",
        driverName: "Mei Ling Tan",
        route: "1 Utama Shopping Centre → TTDI Park",
        payout: 17.60,
        timestamp: new Date(now - 215 * 60 * 1000).toISOString()
      },
      {
        id: "ACT-9005",
        tripId: "TRP-2026-9005",
        driverName: "Nurul Huda",
        route: "Sunway Pyramid → Subang Jaya SS15",
        payout: 19.20,
        timestamp: new Date(now - 185 * 60 * 1000).toISOString()
      }
    ],
    gasConfig: {
      webAppUrl: '',
      autoSyncOnComplete: true,
      syncStatus: 'IDLE'
    }
  };

  fs.writeFileSync(dbFile, JSON.stringify(localDb, null, 2), 'utf-8');
  console.log("✓ Successfully updated local_db.json with 20 dummy trips and drivers.");

  process.exit(0);
}

seed().catch(err => {
  console.error("Seeding error:", err);
  process.exit(1);
});
